### ISSUE TITLE
Null nodes found

### ISSUE THREAD

**Issue by chriskarapapas** [wiberlin/ipfs-crawler#2]
Hello! 
There is a problem running the crawler. Although i have tested every possible case i get this after executing the following command:

export LIBP2P_ALLOW_WEAK_RSA_KEYS="" && go run cmd/ipfs-crawler/main.go

INFO[20:04:07] Thank you for running our IPFS Crawler!      
INFO[20:04:07] Checking whether weak RSA keys are allowed...  weak_RSA_keys=true
INFO[20:04:16] Creating workers...                           numberOfWorkers=5
DEBUG[20:04:16] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=2000
DEBUG[20:04:16] Size of Queue                                 QueueSize=2000
DEBUG[20:04:16] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=4000
DEBUG[20:04:16] Size of Queue                                 QueueSize=4000
DEBUG[20:04:16] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=6000
DEBUG[20:04:16] Size of Queue                                 QueueSize=6000
DEBUG[20:04:16] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=8000
DEBUG[20:04:16] Size of Queue                                 QueueSize=8000
DEBUG[20:04:17] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=10000
DEBUG[20:04:17] Size of Queue                                 QueueSize=10000
INFO[20:04:17] Adding cached peer to crawl queue.            amount=0
INFO[20:04:17] Starting crawl...                            
DEBUG[20:04:17] Adding bootstraps                            
DEBUG[20:04:17] Dispatch crawler request                      node=QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
DEBUG[20:04:17] Dispatch crawler request                      node=QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
DEBUG[20:04:17] Dispatch crawler request                      node=QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
DEBUG[20:04:17] Dispatch crawler request                      node=QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:04:17] Dispatch crawler request                      node=QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
DEBUG[20:04:17] Dispatch crawler request                      node=QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}"
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/udp/4001/quic]}"
DEBUG[20:04:17] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:04:17] Could not connect.                            IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/udp/4001/quic]}" err="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: no good addresses"
DEBUG[20:04:17] Error while crawling                          Error="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: no good addresses"
DEBUG[20:04:18] Could not connect.                            IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}" err="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: all dials failed\n  * [/ip4/104.131.131.82/tcp/4001] failed to negotiate stream multiplexer: remote error: tls: bad certificate"
DEBUG[20:04:18] Error while crawling                          Error="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: all dials failed\n  * [/ip4/104.131.131.82/tcp/4001] failed to negotiate stream multiplexer: remote error: tls: bad certificate"
DEBUG[20:04:27] Could not connect.                            IPFSWorkerID=0 destAddr="{QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: no good addresses"
DEBUG[20:04:27] Error while crawling                          Error="failed to dial QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: no good addresses"
DEBUG[20:04:27] Could not connect.                            IPFSWorkerID=0 destAddr="{QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: no good addresses"
DEBUG[20:04:27] Error while crawling                          Error="failed to dial QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: no good addresses"
DEBUG[20:04:27] Could not connect.                            IPFSWorkerID=0 destAddr="{QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: no good addresses"
DEBUG[20:04:27] Error while crawling                          Error="failed to dial QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: no good addresses"
DEBUG[20:04:27] Could not connect.                            IPFSWorkerID=0 destAddr="{QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: no good addresses"
DEBUG[20:04:27] Error while crawling                          Error="failed to dial QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: no good addresses"
INFO[20:04:27] Stopping crawl...                            
INFO[20:04:27] Crawl finished. Summary of results.           connectable nodes=0 end time:="18-10-20--20:04:27" number of nodes=0 start time="18-10-20--20:04:07"
INFO[20:04:27] Online nodes saved in cache                   File=nodes.cache
christos@christos-VirtualBox:~/Desktop/Ipfscrawler/ipfs-crawler$ export LIBP2P_ALLOW_WEAK_RSA_KEYS="" && go run cmd/ipfs-crawler/main.go > outp.txt
INFO[20:06:02] Thank you for running our IPFS Crawler!      
INFO[20:06:02] Checking whether weak RSA keys are allowed...  weak_RSA_keys=true
INFO[20:06:11] Creating workers...                           numberOfWorkers=5
DEBUG[20:06:11] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=2000
DEBUG[20:06:11] Size of Queue                                 QueueSize=2000
DEBUG[20:06:11] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=4000
DEBUG[20:06:11] Size of Queue                                 QueueSize=4000
DEBUG[20:06:12] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=6000
DEBUG[20:06:12] Size of Queue                                 QueueSize=6000
DEBUG[20:06:12] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=8000
DEBUG[20:06:12] Size of Queue                                 QueueSize=8000
DEBUG[20:06:12] Size of Queue                                 capacity=2000 maxCap=2000 sumCap=10000
DEBUG[20:06:12] Size of Queue                                 QueueSize=10000
INFO[20:06:12] Adding cached peer to crawl queue.            amount=0
INFO[20:06:12] Starting crawl...                            
DEBUG[20:06:12] Adding bootstraps                            
DEBUG[20:06:12] Dispatch crawler request                      node=QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
DEBUG[20:06:12] Dispatch crawler request                      node=QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
DEBUG[20:06:12] Dispatch crawler request                      node=QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb
DEBUG[20:06:12] Dispatch crawler request                      node=QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt
DEBUG[20:06:12] Dispatch crawler request                      node=QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
DEBUG[20:06:12] Dispatch crawler request                      node=QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/udp/4001/quic]}"
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}"
DEBUG[20:06:12] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"
DEBUG[20:06:12] Could not connect.                            IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/udp/4001/quic]}" err="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: no good addresses"
DEBUG[20:06:12] Error while crawling                          Error="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: no good addresses"
DEBUG[20:06:13] Could not connect.                            IPFSWorkerID=0 destAddr="{QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}" err="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: all dials failed\n  * [/ip4/104.131.131.82/tcp/4001] failed to negotiate stream multiplexer: remote error: tls: bad certificate"
DEBUG[20:06:13] Error while crawling                          Error="failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: all dials failed\n  * [/ip4/104.131.131.82/tcp/4001] failed to negotiate stream multiplexer: remote error: tls: bad certificate"
DEBUG[20:06:22] Could not connect.                            IPFSWorkerID=0 destAddr="{QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: no good addresses"
DEBUG[20:06:22] Error while crawling                          Error="failed to dial QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: no good addresses"
DEBUG[20:06:22] Could not connect.                            IPFSWorkerID=0 destAddr="{QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: no good addresses"
DEBUG[20:06:22] Error while crawling                          Error="failed to dial QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: no good addresses"
DEBUG[20:06:22] Could not connect.                            IPFSWorkerID=0 destAddr="{QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: no good addresses"
DEBUG[20:06:22] Error while crawling                          Error="failed to dial QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: no good addresses"
DEBUG[20:06:22] Could not connect.                            IPFSWorkerID=0 destAddr="{QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}" err="failed to dial QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: no good addresses"
DEBUG[20:06:22] Error while crawling                          Error="failed to dial QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: no good addresses"
INFO[20:06:22] Stopping crawl...                            
INFO[20:06:22] Crawl finished. Summary of results.           connectable nodes=0 end time:="18-10-20--20:06:22" number of nodes=0 start time="18-10-20--20:06:02"
INFO[20:06:22] Online nodes saved in cache                   File=nodes.cache

**Comment by harlequix** [comment]
Hi chriskarapapas,

I cannot reproduce the error on my setup. Can you post your distribution and the go version you are using?

**Comment by chriskarapapas** [comment]
Hellp harlequix,
thanks for the response. 
Go Version: go1. 15.3 
Ubuntu    20.04 on oracle vm over Bridged adapter

**Comment by chriskarapapas** [comment]
The most surprising error i think is this
"negotiate stream multiplexer: remote error: tls: bad certificate"

**Comment by harlequix** [comment]
OK, i can reproduce the error on Ubuntu 20.04 with go 1.15.3. Weirdly enough, the crawler works fine on Archlinux and go 1.15.3 and go 1.14. So there is something ubuntu-specific going on.

I'm right now working on implementing the new noise protocol and fixing tls. I will notify you here when it is done.

**Comment by chriskarapapas** [comment]
Same error on Ubuntu 18.04 with go version go1.10.4 linux/amd64.
I installed it just to check whether it works.

**Comment by harlequix** [comment]
@chriskarapapas I have pushed a commit that fixes it at least on my ubuntu test machines. Can you update and try again?

**Comment by chriskarapapas** [comment]
@harlequix  Seems to connect to nodes but i get a lot of errors and still no output data.
Also, does the crawler support a verbose mode? With less "debug output" ?


   ... skipping 78 errors ..."
DEBUG[01:41:08] Error while crawling                          Error="failed to dial QmaerGDgdFbSeojFViVPu5PqjVae73DMKvKjjpMxpu8GUB: all dials failed\n  * [/ip4/182.139.95.104/tcp/56453] dial tcp4 0.0.0.0:33471->182.139.95.104:56453: i/o timeout\n  * [/ip4/182.139.95.104/tcp/57175] dial tcp4 182.139.95.104:57175: i/o timeout\n  * [/ip4/182.139.95.104/tcp/56214] dial tcp4 182.139.95.104:56214: i/o timeout\n  * [/ip4/182.139.95.104/tcp/53911] dial tcp4 0.0.0.0:33471->182.139.95.104:53911: i/o timeout\n  * [/ip4/182.139.95.104/tcp/56857] dial tcp4 0.0.0.0:33471->182.139.95.104:56857: i/o timeout\n  * [/ip4/182.139.95.104/tcp/55254] dial tcp4 0.0.0.0:33471->182.139.95.104:55254: i/o timeout\n  * [/ip4/182.139.95.104/tcp/56922] dial tcp4 182.139.95.104:56922: connect: connection refused\n  * [/ip4/182.139.95.104/tcp/55240] dial tcp4 182.139.95.104:55240: connect: connection refused\n  * [/ip4/182.139.95.104/tcp/54793] dial tcp4 182.139.95.104:54793: connect: connection refused\n  * [/ip4/182.139.95.104/tcp/56406] dial tcp4 182.139.95.104:56406: connect: connection refused\n  * [/ip4/182.139.95.104/tcp/53970] dial tcp4 182.139.95.104:53970: connect: connection refused\n  * [/ip4/182.139.95.104/tcp/54097] dial tcp4 182.139.95.104:54097: i/o timeout\n  * [/ip4/182.139.95.104/tcp/55580] dial tcp4 182.139.95.104:55580: i/o timeout\n  * [/ip4/182.139.95.104/tcp/53732] dial tcp4 0.0.0.0:33471->182.139.95.104:53732: i/o timeout\n  * [/ip4/182.139.95.104/tcp/54358] dial tcp4 0.0.0.0:33471->182.139.95.104:54358: i/o timeout\n  * [/ip4/182.139.95.104/tcp/54247] dial tcp4 0.0.0.0:33471->182.139.95.104:54247: i/o timeout\n    ... skipping 78 errors ..."
DEBUG[01:41:17] Error sending crawl msg.                      IPFSWorkerID=0 destAddr="{QmVB7nuNAmkkPLy4UFecEAyuxJyWV537f9ugr2pGM59LNC: [/ip4/86.192.144.68/tcp/43507 /ip4/86.192.144.68/tcp/3649]}" err="stream reset"
DEBUG[01:41:17] Error while crawling                          Error="stream reset"
DEBUG[01:41:19] Adding newer seen node                        node=QmbBYnbmvvgCz5N4xUchV7vkm3KWpDf2CsumboVYLWocXm
DEBUG[01:41:19] Status of Manager                             Current Request=0 Reports=0 toCrawl=1
DEBUG[01:41:19] Dispatch crawler request                      node=QmbBYnbmvvgCz5N4xUchV7vkm3KWpDf2CsumboVYLWocXm
DEBUG[01:41:19] IPFSWorker connecting to                      IPFSWorkerID=0 destAddr="{QmbBYnbmvvgCz5N4xUchV7vkm3KWpDf2CsumboVYLWocXm: [/ip4/114.40.167.141/tcp/60946]}"
INFO[01:41:20] Periodic info on crawl status                 Connectable nodes=1054 Found nodes=15522 To-crawl-queue=0 Waiting for requests=1
./start_crawl: line 1:  1791 Killed                  ./cmd/ipfs-crawler/crawler
[chris@christos-virtualbox ipfs-crawler]$

**Comment by harlequix** [comment]
You can change the loglevel to "info" in configs/config.yml. 
You can see that the crawler connects but it is killed by the OS. You are seeing this kind of behavious in case of a segfault or when your PC runs out of memory. Can you rerun the crawler and monitor the memory usage?

**Comment by chriskarapapas** [comment]
@harlequix 
              total        used        free      shared  buff/cache   available
Mem:           9874         887        8615          16         371        8729
Swap:           448         407          41


             total        used        free      shared  buff/cache   available
Mem:           9874        3325        5996          19         552        6289
Swap:           448         401          46

              total        used        free      shared  buff/cache   available
Mem:           9874        5276        4021          19         577        4338
Swap:           448         401          46

              total        used        free      shared  buff/cache   available
Mem:           9874        8265        1032          19         577        1349
Swap:           448         401          46

Some snapshots of the free memory during an execution of the crawler. THe free metric goes down to 121 mb but the system freezes, so i am not able to take a snapshot.

**Comment by harlequix** [comment]
Thank you very much. I see the same thing on newer deployment but weirdly enough not on my main development PC. I suspect that some update in a third party module introduced a memory leak. I will investigate and report back when it is fixed

**Comment by harlequix** [comment]
@chriskarapapas I have pushed a fixed for the memory leak. The crawl now runs smoothly on a fresh install of Ubuntu 20.04 and Fedora 33. Please try to run it again. If you have anymore problems, do not hesitate to report them

**Comment by chriskarapapas** [comment]
@harlequix It works, thanks! Some minor observations:

- Still get an error
 ERROR	basichost	failed to resolve local interface addresses	{"error": "route ip+net: netlinkrib: too many open files"}
although the log level is INFO
- Although i performed a series of crawls, in none of them did i find 44000 distinct nodes, as argued in the paper. I did found ~13000 and ~ 830 connectable which is about 6%, as argued in the paper. Is something wrong with crawler or this is a difference in the network?

**Comment by harlequix** [comment]
@chriskarapapas 
- hmmm... I haven't seen this error from this particular place, but the "too many open files" message indicate that you haven't raised the limit of file descriptors (mentioned in the very last point in the readme). If you are on linux, try to raise the limit via ulimit -n unlimited.

- IPFS changed the dht with version 0.5, I think it was. It now runs a dual dht, one for public IP's and one for private IP's. We can only query the public dht and since that update we see significantly fewer peer during our crawls

**Comment by harlequix** [comment]
[link to release notes](https://github.com/ipfs/go-ipfs/releases/tag/v0.5.0)

**Comment by scriptkitty** [comment]
Just a small addition to @harlequix answer: You're right with your objection @chriskarapapas in that the number of discovered nodes seems contradictory to the numbers in the paper.
However, as shown in Table II, roughly 24k nodes out of 44k discovered ones only reported local IPs to the DHT, which is clearly not desirable behavior. The changes introduced with go-ipfs v0.4.23 and later versions aimed at solving this problem, effectively moving those nodes into client mode, where they can no longer be grasped through crawling.

We have a periodic crawl infrastructure setup and your results seem comparable to ours their: http://trudi.weizenbaum.net/

**Comment by chriskarapapas** [comment]
@harlequix @scriptkitty It is not an objection, it is just curiosity. Thank you both for your answers!
@harlequix 
                   - ulimit -n 2048 fixed the "too many open files"
                   -  have you tried statistics on your Ubuntu 20.04 install? Neither docker nor manual install worked for me, although 
                      adding here 

> Rscript -e "install.packages(c(\"data.table\", \"reshape2\", \"ggplot2\", \"scales\", \
>          \"tikzDevice\", \"stringr\", \"pbapply\", \"igraph\", "jsonlite", "tidyr"))"  

                       backslashes around jsonlite and tidyr fixes some problems. Still ,though, it doesn't work!

**Comment by scriptkitty** [comment]
Thanks for pointing that out, I've adapted the eval scripts to the newest version of crawler output in the master branch. Let me know if there are still persisting issues for you!

**Comment by chriskarapapas** [comment]
@scriptkitty Thanks for the  answer, the building procedure works fine! I get the following error during the  report creation though. Is there a minimum amount of output data for the report to be created?

> Rscript plotting/output_sessionLengths.R
> Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
>   no lines available in input
> Calls: LoadDT -> data.table -> read.csv -> read.table
> Execution halted
> Makefile:52: recipe for target 'tables/session_lengths.tex' failed
> make: *** [tables/session_lengths.tex] Error 1
> Finished eval, copying report.pdf to /home/chris/Desktop/ipfs-crawler:
> cp: cannot stat 'eval/plot_data/report.pdf': No such file or directory

**Comment by harlequix** [comment]
hmm @chriskarapapas could you double check if the separator used in the R script and the one used in the csv are the same? I remember a similar error ages ago (script wanted ',' as separator, csv used ';')

**Comment by chriskarapapas** [comment]
@harlequix Indeed scv uses semicolon, shall i change the code of a script from , to ; ?

**Comment by harlequix** [comment]
change it and it should work, IIRC. I thought we fixed that a long time ago sorry for that

**Comment by scriptkitty** [comment]
Are you sure that's the culprit? With > 3 crawls all the scripts run fine for me, no problem with the separator

**Comment by chriskarapapas** [comment]
@harlequix Thx for the answer, can you please be more specific, because I don't really get it! Which script should I change?

**Comment by chriskarapapas** [comment]
@scriptkitty Not sure. The output i am getting is this:
Rscript basic_crawl_information.R
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
Rscript plotting/output_sessionLengths.R
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: LoadDT -> data.table -> read.csv -> read.table
Execution halted
Makefile:52: recipe for target 'tables/session_lengths.tex' failed
make: *** [tables/session_lengths.tex] Error 1
Finished eval, copying report.pdf to /home/chris/Desktop/ipfs-crawler:
cp: cannot stat 'eval/plot_data/report.pdf': No such file or directory
 
When i try to open csv with the libre office i the default separator is  the  semicolon.

**Comment by scriptkitty** [comment]
So there is a ```plot_data/session_lengths.csv```? What's the output of ```head plot_data/session_lengths.csv```?

**Comment by chriskarapapas** [comment]
> So there is a `plot_data/session_lengths.csv`? What's the output of `head plot_data/session_lengths.csv`?

None, it is empty!

**Comment by chriskarapapas** [comment]
> > So there is a `plot_data/session_lengths.csv`? What's the output of `head plot_data/session_lengths.csv`?
> 
> None, it is empty!

@harlequix @scriptkitty I did a clean install and everything seems to work fine! Sorry for the inconvenience and thanks for the overall help!

**Comment by scriptkitty** [comment]
Great to hear that it works now! :) If you use the eval scripts I'd advise you to ```make clean``` before you run a new eval on new data, as the Makefile skips some steps if there's cached data or finalized figures/tables (e.g., in plot_data/, figures/ and tables/).

Thank you for bringing all these points up, that always helps us to improve the software!
